[package]
name = "octothorpe"
version = "0.1.0"
authors = ["root <root@root>"]
edition = "2018"

[dependencies]
jack = { git = "https://github.com/spunge/rust-jack.git" }

[[bin]]
name = "octothorpe"
