[package]
name = "octothorpe"
version = "0.1.0"
authors = ["root <root@root>"]
edition = "2018"

[dependencies]
jack = { git = "https://github.com/spunge/rust-jack.git" }
jack-sys = "0.2.0"

[[bin]]
name = "octothorpe"
